### ISSUE TITLE
gr4vy-react-native doesn't work with Expo

### ISSUE THREAD

**Issue by AlbertWang156** [gr4vy/gr4vy-react-native#35]
I got this error:

<img width="1439" alt="Screenshot 2024-07-02 at 11 34 58 PM" src="https://github.com/gr4vy/gr4vy-react-native/assets/163362483/cc918b4d-6636-4f9d-b2e2-8c900b795dfa">

How can I use it in Expo?

**Comment by luca-gr4vy** [comment]
hey @AlbertWang156, we don't officially support integrating the SDK with Expo yet so we'd have to check that. Please feel free to drop us a line at support@gr4vy.com with your use-case / needs
